services:
  accounts:
    image: "hieptt149/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hieptt-demo
  loans:
    image: "hieptt149/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hieptt-demo
  cards:
    image: "hieptt149/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hieptt-demo
networks:
  hieptt-demo:
    driver: "bridge"
