/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    alias(libs.plugins.jib)
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.spring.boot.actuator)
    implementation(libs.spring.cloud.config.server)
    testImplementation(libs.spring.boot.test)
}

group = "com.hieptt149"
version = "0.0.1-SNAPSHOT"
description = "configserver"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

jib {
    to {
        image = "hieptt149/configserver:s10"
    }
}
